version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betalent-test-api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
    command: >
      sh -c "node ace migration:setup && node ace migration:run && npm run dev"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: betalent-test-mysql-db
    restart: always
    networks:
      - app-network
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_HOST_AUTH_METHOD: trust
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
